name: release

on: push

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build
              run: |
                  python3 -m pip install --upgrade build
                  python3 -m build
                  echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: dist/*
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ env.VERSION }}
